---
abstract: "Hayo Baan's Dist::Zilla configuration"
author:
  - 'Hayo Baan <info@hayobaan.nl>'
build_requires:
  File::Spec: '0'
  File::pushd: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Path::Tiny: '0'
  Test::DZil: '0'
  Test::More: '0.96'
  perl: '5.010'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
  perl: '5.010'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-Author-HAYOBAAN
no_index:
  directory:
    - corpus
provides:
  Dist::Zilla::PluginBundle::Author::HAYOBAAN:
    file: lib/Dist/Zilla/PluginBundle/Author/HAYOBAAN.pm
    version: '0.002'
  Pod::Weaver::PluginBundle::Author::HAYOBAAN:
    file: lib/Pod/Weaver/PluginBundle/Author/HAYOBAAN.pm
    version: '0.002'
requires:
  Dist::Zilla: '5.014'
  Dist::Zilla::Plugin::CheckChangesHasContent: '0'
  Dist::Zilla::Plugin::CheckMetaResources: '0'
  Dist::Zilla::Plugin::CheckPrereqsIndexed: '0'
  Dist::Zilla::Plugin::Clean: '0'
  Dist::Zilla::Plugin::CopyFilesFromBuild: '0'
  Dist::Zilla::Plugin::Git::Check: '0'
  Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch: '0'
  Dist::Zilla::Plugin::Git::Commit: '0'
  Dist::Zilla::Plugin::Git::GatherDir: '0'
  Dist::Zilla::Plugin::Git::NextVersion: '0'
  Dist::Zilla::Plugin::Git::Push: '0'
  Dist::Zilla::Plugin::Git::Tag: '0'
  Dist::Zilla::Plugin::GitHub::Meta: '0'
  Dist::Zilla::Plugin::GitHub::Update: '0'
  Dist::Zilla::Plugin::InstallGuide: '0'
  Dist::Zilla::Plugin::MetaProvides: '0'
  Dist::Zilla::Plugin::MinimumPerl: '0'
  Dist::Zilla::Plugin::MojibakeTests: '0'
  Dist::Zilla::Plugin::OurPkgVersion: '0'
  Dist::Zilla::Plugin::PodWeaver: '0'
  Dist::Zilla::Plugin::ReadmeAnyFromPod: '0'
  Dist::Zilla::Plugin::Run: '0'
  Dist::Zilla::Plugin::RunExtraTests: '0'
  Dist::Zilla::Plugin::SchwartzRatio: '0'
  Dist::Zilla::Plugin::Test::CPAN::Changes: '0'
  Dist::Zilla::Plugin::Test::CPAN::Meta::JSON: '0'
  Dist::Zilla::Plugin::Test::Compile: '0'
  Dist::Zilla::Plugin::Test::DistManifest: '0'
  Dist::Zilla::Plugin::Test::EOL: '0'
  Dist::Zilla::Plugin::Test::Kwalitee: '0'
  Dist::Zilla::Plugin::Test::MinimumVersion: '0'
  Dist::Zilla::Plugin::Test::NoTabs: '0'
  Dist::Zilla::Plugin::Test::Perl::Critic: '0'
  Dist::Zilla::Plugin::Test::Pod::LinkCheck: '0'
  Dist::Zilla::Plugin::Test::Portability: '0'
  Dist::Zilla::Plugin::Test::Synopsis: '0'
  Dist::Zilla::Plugin::Test::UnusedVars: '0'
  Dist::Zilla::Plugin::Test::Version: '0'
  Dist::Zilla::Role::PluginBundle::Easy: '0'
  Getopt::Long: '0'
  Moose: '0.99'
  Pod::Elemental::PerlMunger: '0'
  Pod::Elemental::Transformer::List: '0'
  Pod::Weaver::Config::Assembler: '0'
  namespace::autoclean: '0.09'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/HayoBaan/Dist-Zilla-PluginBundle-Author-HAYOBAAN/issues
  homepage: http://metacpan.org/release/Dist-Zilla-PluginBundle-Author-HAYOBAAN/
  repository: git://github.com/HayoBaan/Dist-Zilla-PluginBundle-Author-HAYOBAAN.git
version: '0.002'
