---
abstract: "Hayo Baan's Dist::Zilla configuration"
author:
  - 'Hayo Baan <info@hayobaan.nl>'
build_requires:
  File::Spec: '0'
  File::pushd: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Path::Tiny: '0'
  Test::DZil: '0'
  Test::More: '0.96'
  perl: '5.010'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
  perl: '5.010'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-Author-HAYOBAAN
no_index:
  directory:
    - corpus
provides:
  Dist::Zilla::PluginBundle::Author::HAYOBAAN:
    file: lib/Dist/Zilla/PluginBundle/Author/HAYOBAAN.pm
    version: '0.001'
  Pod::Weaver::PluginBundle::Author::HAYOBAAN:
    file: lib/Pod/Weaver/PluginBundle/Author/HAYOBAAN.pm
    version: '0.001'
requires:
  Dist::Zilla: '5.014'
  Dist::Zilla::Role::PluginBundle::Easy: '0'
  Getopt::Long: '0'
  Moose: '0.99'
  Pod::Weaver::Config::Assembler: '0'
  namespace::autoclean: '0.09'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/HayoBaan/Dist-Zilla-PluginBundle-Author-HAYOBAAN/issues
  repository: git://github.com/HayoBaan/Dist-Zilla-PluginBundle-Author-HAYOBAAN.git
version: 0.001
